CREATE TABLE IF NOT EXISTS `TEXT` ( 
  `ID_TEXT`         INT(10) NOT NULL PRIMARY KEY,
  `TEXT`            TEXT(1024),
  `DATE_TEXT`       DATE
);

CREATE TABLE IF NOT EXISTS `SITES` ( 
  URL  VARCHAR(40) NOT NULL PRIMARY KEY,
  ID_TEXT       INT(10),
  FOREIGN KEY (ID_TEXT) REFERENCES TEXT(ID_TEXT)
);

CREATE TABLE IF NOT EXISTS `CATEGORIES` ( 
  `ID_CATEGORY`       INT(10) NOT NULL PRIMARY KEY,
  `NAME`              VARCHAR(40),
  `DESCRIPTION`       VARCHAR(40),
  `URL`               VARCHAR(40),
  FOREIGN KEY (URL) REFERENCES SITES(URL)
);